## Single layer neural networks

In [1]:
import torch

In [2]:
def activation(x):
    """
    :param x: torch.Tensor
    :return: result of Sigmoid activation function
    """
    return 1 / (1 + torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7)  # Set random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and true bias term
bias = torch.randn((1, 1))

In [4]:
## calculate the output of this network using using weights and bias tensors
#y =  activation(torch.sum(features * weights) + bias)
y =  activation((features * weights).sum() + bias)

y

tensor([[0.1595]])

### Same operation by:
using element wise multiplication and taking the sum in two separate operations

### Matrix multiplication:
Can be done with `torch.mm()` or `torch.matmul()` but the latter is more complicated because supports broadcasting.
`torch.mm()` throws error immediately

If we try `torch.mm(features, weights)` we will get and error with:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-8f55c3abfe5a> in <module>
----> 1 torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorMath.cpp:197
    
This because in matrix multiplication the first expects the number of columns to match the number of rows of the second, so it must be m1: [1 x 5], m2: [5 x 1]
    
A good way to know the expected values is by printing the shape of the tensor by calling `torch.shape`

In [5]:
torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorMath.cpp:197

To fix this is necessary to reshape the tensor.
It is possible to use `weights.reshape()`, `weights.resize_()` and `weights.view()`

In [6]:
weights = weights.view(5, 1)

y =  activation(torch.mm(features, weights) + bias)

y

tensor([[0.1595]])

## Multi layers neural networks

In [7]:
### Generate some data
torch.manual_seed(7)  # Set random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in out network
n_input = features.shape[1] # Numbe rof input units, must match the number of input features
n_hidden = 2 # Number of hidden units
n_output = 1 # Number of output units

# Wheigh for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
#Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [8]:
h =  activation(torch.mm(features, W1).sum() + B1)
output =  activation(torch.mm(h, W2).sum() + B2)

output

tensor([[0.3627]])

## Numpy to Torch and back

In [9]:
import numpy as np

a = np.random.rand(4, 3)
a

array([[0.82059187, 0.65470913, 0.73413166],
       [0.54714787, 0.31277744, 0.59736526],
       [0.96850987, 0.13648742, 0.58278314],
       [0.01386349, 0.789374  , 0.47095258]])

In [10]:
b = torch.from_numpy(a)
b

tensor([[0.8206, 0.6547, 0.7341],
        [0.5471, 0.3128, 0.5974],
        [0.9685, 0.1365, 0.5828],
        [0.0139, 0.7894, 0.4710]], dtype=torch.float64)

In [11]:
b.numpy()

array([[0.82059187, 0.65470913, 0.73413166],
       [0.54714787, 0.31277744, 0.59736526],
       [0.96850987, 0.13648742, 0.58278314],
       [0.01386349, 0.789374  , 0.47095258]])

In [12]:
# Multiply PyTorch tensor by 2, in place
b.mul_(2)

tensor([[1.6412, 1.3094, 1.4683],
        [1.0943, 0.6256, 1.1947],
        [1.9370, 0.2730, 1.1656],
        [0.0277, 1.5787, 0.9419]], dtype=torch.float64)

In [14]:
# Numpy array matches values from tensor because they share same space in memory,
# somthing to keep in mind
a

array([[1.64118373, 1.30941827, 1.46826331],
       [1.09429574, 0.62555487, 1.19473051],
       [1.93701975, 0.27297483, 1.16556628],
       [0.02772698, 1.57874801, 0.94190516]])

In [24]:
c = b.numpy()
print(np.array_equal(a,c))

True
